name: dft
description: Calculate Discrete Fourier Transform using Radix2 Algorithm.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.16+30

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_dynamic_theme: ^2.2.0
  complex: ^0.7.2
  syncfusion_flutter_charts: ^25.1.38
  url_launcher: ^6.1.11
  dynamic_color: ^1.6.3
  flutter_animate: ^4.1.1+1
  go_router: ^14.0.1

dev_dependencies:
  flutter_lints: ^3.0.1
  lint: ^2.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMonoNL-Medium.ttf
