name: dft
description: Calculate Discrete Fourier Transform using Radix2 Algorithm.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+8

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.1.1
  get_storage: ^2.0.1
  complex: ^0.7.2
  syncfusion_flutter_charts: ^21.2.4
  url_launcher: ^6.1.11
  dynamic_color: ^1.6.3
  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  lint: ^2.1.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "android/app/src/main/launcher-playstore.png"

flutter:
  uses-material-design: true

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMonoNL-Medium.ttf
