name: dft
description: Calculate Discrete Fourier Transform using Radix2 Algorithm.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.4+18

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_dynamic_theme: ^2.2.0
  complex: ^0.7.2
  syncfusion_flutter_charts: ^23.1.36
  url_launcher: ^6.1.11
  dynamic_color: ^1.6.3
  flutter_animate: ^4.1.1+1
  go_router: ^11.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  lint: ^2.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMonoNL-Medium.ttf
