name: dft
description: Calculate Discrete Fourier Transform using Radix2 Algorithm.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Internal version + Google Play Store build number (unique int)
version: 1.2.1+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.1.1
  get_storage: ^2.0.1
  complex: ^0.7.2
  syncfusion_flutter_charts: ^20.1.57
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  lint: ^1.5.3

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
